title: Robotics Laboratory
description: Quickstart tutorials for the Robotics Laboratory course.
theme: just-the-docs

url: https://marco-faroni.github.io/Robotics-Laboratory-Polimi

aux_links:
  Course repository: https://github.com/marco-faroni/Robotics-Laboratory-Polimi
